version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@assemblyscript/loader"
    versions:
    - 0.17.14
    - 0.18.0
    - 0.18.10
    - 0.18.11
    - 0.18.12
    - 0.18.13
    - 0.18.14
    - 0.18.15
    - 0.18.16
    - 0.18.18
    - 0.18.19
    - 0.18.21
    - 0.18.22
    - 0.18.23
    - 0.18.24
    - 0.18.25
    - 0.18.26
    - 0.18.27
    - 0.18.28
    - 0.18.3
    - 0.18.4
    - 0.18.6
    - 0.18.7
    - 0.18.9
  - dependency-name: assemblyscript
    versions:
    - 0.17.14
    - 0.18.0
    - 0.18.10
    - 0.18.11
    - 0.18.12
    - 0.18.13
    - 0.18.14
    - 0.18.15
    - 0.18.16
    - 0.18.18
    - 0.18.19
    - 0.18.21
    - 0.18.22
    - 0.18.23
    - 0.18.24
    - 0.18.25
    - 0.18.26
    - 0.18.27
    - 0.18.28
    - 0.18.3
    - 0.18.4
    - 0.18.6
    - 0.18.7
    - 0.18.9
  - dependency-name: np
    versions:
    - 7.2.0
    - 7.3.0
    - 7.4.0
  - dependency-name: iso-random-stream
    versions:
    - 2.0.0
  - dependency-name: tape
    versions:
    - 5.1.1
    - 5.2.0
    - 5.2.1
  - dependency-name: buffer
    versions:
    - 6.0.3
